[project]
name = "demofirecrawl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "firecrawl>=2.15.0",
    "firecrawl-py>=2.15.0",
    "requests>=2.32.4",
]
